sudo usermod -aG docker $USER
sudo systemctl restart docker
docker ps

How to run Docker commands without sudo?
Make sure docker is installed and system is updated (This is already been completed as a part of previous tasks):
sudo usermod -a -G docker $USER
Reboot the machine.