nginx Dockerfile

-----------------

FROM node:12.2.0-alpine
WORKDIR app
COPY . .
RUN npm install
RUN npm run test
EXPOSE 8000
CMD ["node","app.js"]

--------------------

Multi Stage Docker Build

-------------------------

FROM python:3.9 AS big-stage

WORKDIR /app

COPY ..

FROM python:3.9-slim-bullseye
COPY --from=big-stage /app /app
RUN pip install flask

CMD ["python","app.py"]
~   
-------------------------
Django todo app

FROM python:3

WORKDIR /data

RUN pip install django==3.2

COPY . .

RUN python manage.py migrate

EXPOSE 8000

CMD ["python","manage.py","runserver","0.0.0.0:8000"]

-------------------                     
